# Generated by Django 2.2.12 on 2020-04-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
